// ES5 CLEAR --- ES6 ...
// import './base'
// ES5 TODO [64 位浮点数, 数值范围] --- ES6 ...
// import './number'
// ES5 TODO [字符集, Base64 转码] --- ES6 ...
// import './string'
// ES5 CLEAR --- ES6 ...
// import './object'
// ES5 CLEAR --- ES6 ...
// import './function'
// ES5 CLEAR --- ES6 ...
// import './array'
// ES5 CLEAR --- ES6 ...
// import './arithmetic-operator'
// ES5 CLEAR --- ES6 ...
// import './comparison-operator'
// ES5 CLEAR --- ES6 ...
// import './boolean-operator'
// ES5 TODO [any] --- ES6 ...
// import './binary-operator'
// ES5 CLEAR --- ES6 ...
// import './other-operator'
// ES5 TODO --- ES6 ...
// import './conversion'
