// ES5 CLEAR --- ES6 ...
// import './base'
// ES5 TODO [64 位浮点数, 数值范围] --- ES6 ...
// import './base-number'
// ES5 TODO [字符集, Base64 转码] --- ES6 ...
// import './base-string'
// ES5 CLEAR --- ES6 ...
// import './base-object'
// ES5 CLEAR --- ES6 ...
// import './base-function'
// ES5 CLEAR --- ES6 ...
// import './base-array'

// ES5 CLEAR --- ES6 ...
// import './operator-arithmetic'
// ES5 CLEAR --- ES6 ...
// import './operator-comparison'
// ES5 CLEAR --- ES6 ...
// import './operator-boolean'
// ES5 TODO [any] --- ES6 ...
// import './operator-binary'
// ES5 CLEAR --- ES6 ...
// import './operator-other'

// ES5 CLEAR --- ES6 ...
// import './conversion'

// ES5 CLEAR --- ES6 ...
// import './error'
// ES5 TODO [console, 控制台 API] --- ES6 ...
// import './console'
