// ES5 CLEAR --- ES6 ...
// import './base'
// ES5 TODO [64 位浮点数, 数值范围] --- ES6 ...
// import './number'
// ES5 TODO [字符集, Base64 转码] --- ES6 ...
// import './string'
// ES5 CLEAR --- ES6 ...
// import './object'
// ES5 TODO --- ES6 ...
import './function'
